---

- name: Deploy website from Github
  hosts: ubuntu, centos
  become: true
  vars: 
    githud_repo_url: https://github.com/Joseph789-BIT/Assignment3.git
    destination_path: "/var/www/html"

  tasks: 
   - name: Install git
     package:
       name: git
       status: present

   - name: Remove existing directory
     file:
       path: "/var/www/html"
       status: absent

   - name: Clone Github repository
     git:
       repo: https://github.com/Joseph789-BIT/Assignment3.git
       dest: "/var/www/html"
       version: main
     register: git_clone_result

   - name: Restart Apache
     service:
       name: "{{ 'apache2' if ansible_os_family -- 'Debian' else 'httpd' }}"
       state: restarted    



  ;