--- 
- hosts: ubuntu
  become: true
  vars:
    github_repo_url: https://github.com/Joseph789-BIT/Assignment-3.git
    destination_path: /var/www/html

  tasks:

    - name: Install Apache
      package:
        name: apache2 
        state: latest

    - name: Copy additional HTML file to /var/www/html
      copy:
        src: /C:Users/USER/Documents/Assignment/assignment 3/indexx.html
        dest: /var/www/html/


- hosts: centos
  become: true

  tasks:

    - name: Copy additional HTML file to /var/www/html
      copy:
        src: /C:Users/USER/Documents/Assignment/assignment 3/indexx.html
        dest: /var/www/html/

    - name: Install Apache
      yum:
       name: httpd
       state: latest

    - name: Start Apache 
      service:
        name: httpd
        state: started 

    - name: Enable Apache
      service:
        name: httpd
        enabled: yes
      
  