--- 
- hosts: ubuntu
  become: true
  vars:
    github_repo_url: https://github.com/Joseph789-BIT/Assignment-3.git
    destination_path: /var/www/html

  tasks:

    - name: Install Apache
      package:
        name: apache2 
        state: latest


- hosts: centos
  become: true
  vars:
    github_repo_url: https://github.com/Joseph789-BIT/Assignment-3.git
    destination_path: /var/www/html

  tasks:

    - name: Install Apache
      yum:
       name: httpd
       state: latest

    - name: Start Apache 
      service:
        name: httpd
        state: started 

    - name: Enable Apache
      service:
        name: httpd
        enabled: yes
      
  