--- 
- hosts: ubuntu
  become: true
  tasks:

    - name: Install Apache
      package:
        name: apache2 
        state: latest

    - name: Install git
      package:
        name: git
        state: present


- hosts: centos
  become: true
  vars:
    github_repo_url: https://github.com/Joseph789-BIT/Assignment-3
    destination_path: /var/www/html
  tasks:
  
    - name: Install Apache
      yum:
       name: httpd
       state: latest

    - name: Start Apache 
      service:
        name: httpd
        state: started 

    - name: Install git
      package:
        name: git
        state: present

    - name: Enable Apache
      service:
        name: httpd
        enabled: yes

    - name: Clone github repository
      git:
        repo: https://github.com/Joseph789-BIT/Assignment-3/blob/main/assignment%203/index.html
        dest: /var/www/html
        force: yes
      
  