--- 
- hosts: ubuntu
  become: true
  tasks:

    - name: Install Apache
      package:
        name: apache2 
        state: latest

    - name: Install git
      package:
        name: git
        state: present


- hosts: centos
  become: true
  tasks:
  
    - name: Install Apache
      yum:
       name: httpd
       state: latest

    - name: Start Apache 
      service:
        name: httpd
        state: started 

    - name: Install git
      package:
        name: git
        state: present

    - name: Enable Apache
      service:
        name: httpd
        enabled: yes
      
  