---

- hosts: all
  become: true 
  tasks:

  - name: install apache2 package (ubuntu and centos)
    tag: ubuntu,centos,apache
    package: 
     name: apache2
     state: latest

  - name: Start Apache for centos
      service:
        name: "{{ Apache_service_name }}"
        state: started
      when: ansible_distribution == 'centos'

  - name: Enable Apache for centos
      service:
        name: "{{  }}"
        enabled: yes
      when: ansible_distribution == 'centos'    
  


