---
- hosts: all
  become: true
  tasks:

    - name: Install Apache (Ubuntu and CentOS)
      tags: ubuntu,centos,apache
      package:
        name: apache2 and httpd
        state: present

    - name: Start Apache for centos
      service:
        name: httpd
        state: started 
        when: ansible_distribution == 'centos'

    - name: Enable Apache for centos
      service:
        name: httpd
        enabled: yes
        when: ansible_distribution == 'centos'
  