---
- hosts: all
  become: true
  tasks:

    - name: Install apache2 package (ubuntu and centos)
      tags: 
        - ubuntu
        - centos
        - apache
      package: 
        name: apache2
        state: latest

    - name: Start Apache for centos
      service:
        name: httpd
        state: started

    - name: Enable Apache for centos
      service:
        name: httpd
        enabled: yes
