--- 
- hosts: ubuntu
  become: true
  vars:
    github_repo_url: https://github.com/Joseph789-BIT/Assignment3.git
    destination_path: /var/www/html
  tasks:

    - name: Install Apache
      package:
        name: apache2 
        state: latest

    - name: Install git
      package:
        name: git
        state: present
    
    - name: Remove existing directory
      file:
       path: /var/www/html
       state: absent

    - name: add php support for apache
      package:
       name: libapache2-mod-php
       state: latest
    

    - name: Clone github repository
      git:
        repo: https://github.com/Joseph789-BIT/Assignment3.git
        dest: /var/www/html
        force: yes


  handlers:
    - name: restart web server
      service:
        name: apache2
        state: restarted

      

- hosts: centos
  become: true
  vars:
    github_repo_url: https://github.com/Joseph789-BIT/Assignment3.git
    destination_path: /var/www/html/
  tasks:
  
    - name: Install Apache
      yum:
       name: httpd
       state: latest

    - name: Remove existing directory
      file:
       path: /var/www/html/
       state: absent
    

    - name: Clone github repository
      git:
        repo: https://github.com/Joseph789-BIT/Assignment3.git
        dest: /var/www/html/
        force: yes

    - name: Start Apache 
      service:
        name: httpd
        state: started 

    - name: Install git
      package:
        name: git
        state: present

    - name: Enable Apache
      service:
        name: httpd
        enabled: yes

  handlers:
    - name: restart web server
      service:
        name: httpd
        state: restarted

  